### PR TITLE
Include stdio in futil header

### PR DESCRIPTION
**Pull request by leobiscassi**
This PR fix the problem in bioconda PR [#1929](https://github.com/bioconda/bioconda-recipes/pull/1929), can you please merge it?

### CODE REVIEW

**Comment by leobiscassi** [comment]
@rodrigofaccioli after merge it, can you please create a new release with this changes?

**Comment by rodrigofaccioli** [comment]
Hi @leobiscassi,
I'll send this task to @Hakory since he is merging others pull request. 
Please, @Hakory added this pull request and inform me when all pull request is working to build new version.

Thanks,

**Comment by leobiscassi** [comment]
Hi @rodrigofaccioli, thanks!

**Comment by leobiscassi** [comment]
Hello @Hakory, any response? Thanks in advance.

**Pull request merged**
